on: [push]

jobs:
  build-blog:
    runs-on: ubuntu-latest
    name: "Build and deploy blog"
    steps:
      - name: "Check out repository"
        uses: actions/checkout@v3
        with:
          submodules: "true"
      - name: "Setup everything"
        run: |
          sudo locale-gen de_DE
          sudo locale-gen de_DE.UTF-8
          sudo update-locale LANG=de_DE.UTF-8
      - name: "Build site"
        uses: kytta/zola-build-pages@v1
        with:
          zola-version: "0.18.0"
          output-dir: "./output"
      - name: "Deploy site"
        if: ${{ github.ref_name == 'main' }}
        uses: burnett01/rsync-deployments@7.0.1
        with:
          switches: -rav --delete
          path: output/
          remote_path: /var/www/virtual/n4th4n/html/bullenscheisse.de/
          remote_host: chiron.uberspace.de
          remote_user: n4th4n
          remote_key: ${{ secrets.SSH_KEY }}