on: [push]

jobs:
  build-blog:
    runs-on: ubuntu-latest
    name: "Build and deploy blog"
    steps:
      - name: "Check out latest commit"
        uses: actions/checkout@v4
        with:
          submodules: "true"
          fetch-depth: 1
      - name: "Setup everything"
        run: |
          sudo locale-gen de_DE
          sudo locale-gen de_DE.UTF-8
          sudo update-locale LANG=de_DE.UTF-8
      - name: "Build site"
        uses: kytta/zola-build-pages@v1
        with:
          zola-version: "0.19.1"
          output-dir: "./public"
      - name: "Deploy site"
        if: ${{ github.ref_name == 'main' }}
        uses: burnett01/rsync-deployments@7.0.1
        with:
          switches: -rav --delete
          path: public/
          remote_path: /var/www/virtual/n4th4n/bullenscheisse.de
          remote_host: chiron.uberspace.de
          remote_user: n4th4n
          remote_key: ${{ secrets.SSH_KEY }}